version: '2'
services:
  db:
    restart: always
    image: postgres:11.2-alpine
    command: postgres -c max_connections=300 -c log_directory='pg_log' -c log_statement='all' -c logging_collector=on
    container_name: nutrients-db
    ports:
      - 5433:5432
    environment:
      - TZ=${TIMEZONE}
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
