spring:
  main:
    allow-bean-definition-overriding: false
  jackson:
    property-naming-strategy: SNAKE_CASE
  jpa:
    properties:
      hibernate.enable_lazy_load_no_trans: false
      hibernate.temp.use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: none
      properties:
        hibernate.format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/food
    username: postgres
    password: postgres

server:
  port: 8090

web:
  auth:
    #    Время жизни аксесс токена - пол года
    accessTokenValiditySeconds: 15768000
    #    Время жизни рефреш токена - год
    refreshTokenValiditySeconds: 15768000
    #    Секретный ключ для авторизации
    secret: SeC554KK5

